# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 68c9fb07c7246a89db7c81a311e96bc071107a7d3f95096f67497d21da8a60ffdd44172f1565349503783d99660b3302ba168e5573ffc7cbc0820339f942aa4f
  slack:
    app_id: '24633606786.24636235505'
    app_secret: '506b2c827220a89ca10b4b979bdce0db'

test:
  domain_name: example.com
  secret_key_base: f2db02c3c38a0bb6c0f27e9b7b97174d3ef54847f670518c23657ef10c3db576d4c49b4e7927ca16b2569d2c06bdfc41d7ce1b6a10fa4aa41e200bb54209e3b3
  slack:
    app_id:
    app_secret:
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack:
    app_id:
    app_secret:
